### ISSUE TITLE
Undefined use of max-stale

### ISSUE THREAD

**Issue by philandstuff** [openregister/specification#1]
Example 8 has the following response:

```
HTTP/1.1 200 OK
Date: Fri, 22 Jan 2016 08:00:08 GMT
Link: </school/12345/entries>; rel="version-history"
Cache-Control: max-stale=31536000
Content-Type: application/json
Content-Security-Policy: default-src 'self'
Cache-Control: no-transform
X-Xss-Protection "1; mode=block"
X-Frame-Options "SAMEORIGIN"
X-Content-Type-Options "nosniff"
Vary: Accept-Encoding
Content-Length: 522
```

but max-stale is [only defined as a request directive](https://tools.ietf.org/html/rfc7234#section-5.2), not a response directive.

**Comment by psd** [comment]
Thanks. Bad cut and paste on my part. 

Let's hold off raising issues here for now. Once the spec is more complete we I (and other editors) can take more care over managing git history and act within a working group who will formally process any issues.
