### ISSUE TITLE
Do we provide downloads in tar.gz or [ZIP] (the ISO/IEC 21320-1:2015 profile is open)?

### ISSUE THREAD

**Issue by torgo** [openregister/specification#14]

**Comment by philandstuff** [comment]
.zip is horrible in a number of ways -- for example, it doesn't support timestamps with an odd number of seconds.

I'd propose that we start with tar.gz (or bz2, or xz) and add zip later if there's a need.

**Comment by andyjpb** [comment]
We have .zip and we have no plans to provide anything else.
