### ISSUE TITLE
We use semicolons to separate fields in a TSV/CSV value. Is this the best delimiter to use?

### ISSUE THREAD

**Issue by torgo** [openregister/specification#22]

**Comment by philandstuff** [comment]
The w3c CSV-on-the-web recommendation has the idea of a [column separator](http://w3c.github.io/csvw/syntax/#dfn-column-separator) which is what we're using semicolons for.  One possible answer to this issue would be to just publish some CSVW metadata defining our field delimiter (comma) and column separator (semicolon), and then we're relatively free to choose whatever we like.
