### ISSUE TITLE
IMPLEMENTATION the path to an item is currently implemented as /hash/{item-hash} and returns a record, not an item.

### ISSUE THREAD

**Issue by torgo** [openregister/specification#3]

**Comment by philandstuff** [comment]
we've got a card to fix this, will be played soon

**Comment by philandstuff** [comment]
Fixed. [Example](https://country.register.gov.uk/item/sha-256:466d194d5100532edd115e3f0035967b09bc7b7f5fc444166df6f4a5f7cb9127)
