### ISSUE TITLE
How are hierarchical relationships represented?

### ISSUE THREAD

**Issue by pmackay** [openregister/specification#35]
I'm not sure if this is considered in or out of scope. For example, in http://food-premises-type.openregister.org/, what if there was a need to add "Fast food restaurant" and "Chinese restaurant" as sub-types of "Restaurant" (and so on)? How to represent the parent-child relationship? (broader, narrower in SKOS terms)

**Comment by psd** [comment]
This is data modelling issue which will emerge as we work with custodians to build registers.
