### ISSUE TITLE
What order should /entries be in?

### ISSUE THREAD

**Issue by philandstuff** [openregister/specification#41]
Should the `/entries` resource start at entry-number 1 and go up, or start at the latest entry and go down?

This relates to #7 as well.

**Comment by psd** [comment]
Given the most common use-case is as the basis of a feed, I'd say in descending order, so the first page of /entries would be the latest entries.

**Comment by philandstuff** [comment]
my thinking is that it should be in ascending order, as that's the order you need to replay events if you're indexing them.
