### ISSUE TITLE
Primary key guidance

### ISSUE THREAD

**Issue by pmackay** [openregister/specification#43]
It would be useful to add a bit more guidance on how the primary keys should be defined for a new register. Are there several patterns:
- Use an obvious key where one exists, e.g. 2 letter country names. 
- Create a slug based on real name (approach used for https://public-body.register.gov.uk/?)
- Invent a new key (has this been done for any registers so far? If so, what is the suggested method of doing it?)

Could some suggestions on this go into the specification?

Also, is it possible to add specific documentation for the primary key field defining what it represents? So http://field.openregister.org/field/address should say its the UPRN of the address, rather than describe the address record more generally. Or have both?

**Comment by philandstuff** [comment]
I agree that some guidance on this should exist somewhere. I'm not sure if this specification is the right place for it since its focus is on the technical implementation, though @psd might be able to confirm?

**Comment by psd** [comment]
I'm closing this issue as the specification is not the place to constrain the contents of the key, or how it will be used in modelling data.

We're evolving guidance on, but for the moment this is the primary concern of the registers design authority, working with custodians.

**Comment by pmackay** [comment]
@psd @philandstuff thanks for the clarification. Could I please check:

Is there currently any other repo/place where more general guidance is being gathered? Or is that future work?

> this is the primary concern of the registers design authority, working with custodians.

Partly I asked this and #35 because these are questions that came up for me thinking about how some of the stuff I'm doing on waste standards might fit into registers. I'm actively developing some ideas on that that I'd like to put forward, but I certainly wouldnt be a custodian of such registers. Is there scope for exploring questions like this in a wider community scope? I totally understand if not, just useful to clarify.
