### ISSUE TITLE
Experimental record-proof-resource and records-proof-resource

### ISSUE THREAD

**Issue by michaelabenyohai** [openregister/specification#46]
The record-proof-resource (https://openregister.github.io/specification/#record-proof-resource) and records-proof-resource (https://openregister.github.io/specification/#records-proof-resource) are based on the Google's experimental Verifiable Map and therefore the openregister implementation of these resources is also experimental.

Currently there is no open source implementation of the Verifiable Map available but Google may be including a Verifiable Map in a library written in Go in the future.

**Comment by arnau** [comment]
Closed because #78
