### ISSUE TITLE
Entry timestamp semantics are not defined

### ISSUE THREAD

**Issue by philandstuff** [openregister/specification#48]
We have an `entry-timestamp` field but we haven't defined what time it means.  Time that the entry was added to the register? Time the entry "takes effect"? Some other time?

**Comment by philandstuff** [comment]
@johnollier raised this again today

**Comment by arnau** [comment]
Currently, all known minting processes use the `entry-timestamp` as the time the entry was minted (hence added to the Register).

Based on usage, the meaning of the `entry-timestamp` should be "the time the entry was added to the Register".
