### ISSUE TITLE
§9.4 datetime is timezone ambiguous

### ISSUE THREAD

**Issue by kevinmarks** [openregister/specification#49]
Although it says they MUST be UTC, this is not represented. Either allow a explicit +/-HH:MM timezone offset, or require a trailing Z. Otherwise many systems will interpret this in local time, and more particularly, systems will write in local time unless forced to behave correctly. (This may be more obvious for me as in California I have seen so many DBs and APIs with an implicit -07:00 or -08:00 on their timestamps).

http://openregister.github.io/specification/#datetime-datatype

**Comment by psd** [comment]
Our datetime datatype is designed to be compatible with ISO8601 but offer ambiguity, eg. the start date and time for a country could be midnight, but be unknown, in which case it's just a date. 

We're less worried about California given our domain is firmly HMG but supporting i18n and l10n is something we definitely want to do. We have the timestamp for precise dates and times, and that must have a Z suffix, but I'll add some text to say if a datetime includes a time it must have the Z suffix.
