### ISSUE TITLE
Define what URL a register lives at

### ISSUE THREAD

**Issue by philandstuff** [openregister/specification#55]
Currently, if you have a CURIE such as `company:01234567`, that resolves to `https://country.register.gov.uk/record/01234567` (in the main environment, though it will be different for alpha registers). We don't document this process of resolution anywhere in the specification.

Also, can we do this in such a way that alpha registers can refer to beta registers?

**Comment by arnau** [comment]
CUIRE expansion and catalogue are addressed in the "next" specification.
