### ISSUE TITLE
Reactivate Inline GitHub Issues

### ISSUE THREAD

**Issue by tabatkins** [openregister/specification#56]
Heya! Bikeshed's author here, just letting you know that you should be able to turn `GitHub Inline Issues` back on now. (Turned off in https://github.com/openregister/specification/commit/58cef44736f7c5e5333b624a02fa0e742bec51f3.)  Bikeshed now caches the issues it finds, so unless the issue was changed since you last generated the spec, regenning doesn't count any of them against your limit.

As for the styling issue you're running into, you can negate that easily with a `.issue > .marker { text-transform: none !important; }` to override the rule coming from the default Bikeshed stylesheet. I think it's a bug in Bikeshed's stylesheet, too, but I try to stay aligned with the W3C stylesheet, so I'll be filing an issue to get the W3C stylesheet changed shortly.

**Comment by philandstuff** [comment]
Thanks for letting us know!

I think we're happy with the existing behaviour rather than switching the live issues back on, so I'll mark this issue as closed.
