### ISSUE TITLE
IETF GeoJSON now published

### ISSUE THREAD

**Issue by PeterParslow** [openregister/specification#63]
IETF have now moved their GeoJSON spec from 'draft' to RFC - https://tools.ietf.org/html/rfc7946
I'm pretty sure none of the technical details that are used in the register spec have changed from the Butler draft. So the fix is simply to reference the RFC rather than the draft.

There are some subtle changes elsewhere, which I don't believe impact the register spec: 
- IETF GeoJSON coordinates can **only** be in CRS84 (longitude, latitude, as traditional in north America)
- ISO/OGC polygons (as implemented in most spatial databases) must be co-planar ("flat"); GeoJSON doesn't have that constraint, which can lead to surprise faults when processing them (except in a 2D world).

**Comment by arnau** [comment]
Thanks @PeterParslow I updated the reference in the specification.

We are still considering if GeoJSON is the right choice for Registers.
