### ISSUE TITLE
 if /records and /items are sets, what does that mean for pagination?

### ISSUE THREAD

**Issue by torgo** [openregister/specification#8]

**Comment by philandstuff** [comment]
Also: what happens if a register is updated while a client is paginating through `/records`?

**Comment by arnau** [comment]
Even thought they are sets, they can have a strict order defined by the implementation. For example, in  ORJ, `/items` will always return the same order. https://github.com/openregister/openregister-java/blob/master/doc/arch/adr-008-items-resource.md

The spec doesn't require (MUST) to have a consistent order but it suggests the implementation should do it. Note that this change is part of the "next" effort to stabilise the specification.
