### ISSUE TITLE
Header example shows wrong resource 

### ISSUE THREAD

**Issue by gidsg** [openregister/specification#85]
# Steps to reproduce
go to: https://openregister.github.io/specification/#http-headers

# Actual Results
Header example claims to be
> HTTP headers for the §11.1 JSON representation of an immutable §3.1 Item resource:

but example that follows is actually for an Entries resource: `/school/12345/entries` 

![screen shot 2018-08-16 at 17 28 25](https://user-images.githubusercontent.com/1764158/44221625-f21e8000-a179-11e8-9093-d681e60f6cfb.png)

# Expected Results

Example is for Item resource.

**Comment by arnau** [comment]
Thanks, I'll fix it.

Note that the "next" specification

**Comment by arnau** [comment]
The HTTP header example was intended for an item but was a record.
