### ISSUE TITLE
IMPLEMENTATION /items isn’t yet implemented. There may not be a need for this resource as it’s available in the archive.

### ISSUE THREAD

**Issue by torgo** [openregister/specification#9]

**Comment by frankieroberto** [comment]
@torgo I've been using the registers API to collect the full version history for each record (use case: to collect 'previous names' for an entry for use as synonyms in search), and having a `/items` endpoint would have made this much more efficient. As it is, I have to request `/entries`, and then do a separate HTTP request for each item – which is fairly slow.

**Comment by arnau** [comment]
@frankieroberto noted, thanks!

**Comment by arnau** [comment]
`/items` is in the backlog for being implemented in ORJ.
